image: node:8.4.0
pipelines:
  branches:
    master:
      - step:
          script:
            # Note: in master, this script will rebase you onto latest origin/master
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd build/ci-scripts && bolt stop-if-older-build)
            - bolt build
            - bolt lint
            - bolt typecheck
            - bolt test:ci
            - bolt test:browser:browserstack
            - bolt release
            - (cd build/ci-scripts && bolt restart-stopped-build)

  default:
    - step:
        script:
          - source ./build-setup.sh
          - bolt install --pure-lockfile
          - bolt build
          - bolt lint
          - bolt typecheck
          - bolt test:ci
          - bolt test:browser:browserstack
          # We have to disable the deploy step atm, but we can still build to ensure we dont
          # break the website
          - (cd website && bolt build)
          # - (cd website && bolt deploy-staging:no-minimize)

  custom: # Pipelines that can be scheduled or triggered manually

    # This should only be called by a scheduled build
    build-website-production:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd website && bolt deploy)

    # Adding this so we can test deploying with manual steps
    build-website-staging:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd website && bolt deploy:staging)
